name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checout code
        uses: actions/checkout@v4

      - name: Set upPython
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r app/requirements.ext

      - name: Run tests
        run: pytest tests/ -v         